### ISSUE TITLE
Upgrade from alpha to v5 break android application : Unable to resolve "./NavigationContainer" 

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation-4#6634]
I have tried to upgrade from :

```
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, Android and web
| @react-navigation/native       | 5.0.0-alpha.41
| @react-navigation/stack         | 5.0.0-alpha.63
| @react-navigation/drawer       | 5.0.0-alpha.41
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.32
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | SDK36
| node                           | v13.5.0
| npm or yarn                    | 6.13
```

To

```
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, Android and web
| @react-navigation/native       | 5.0.0
| @react-navigation/stack         | 5.0.0
| @react-navigation/drawer       | 5.0.0
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.32
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | SDK36
| node                           | v13.5.0
| npm or yarn                    | 6.13
```

![image](https://user-images.githubusercontent.com/1866564/73908446-4f614080-48dc-11ea-83f4-c198dd74365d.png)

I had a first warning to use `NavigationContainer` instead of `NavigationNativeContainer`

After that, the android was not able to run and my expo logs say:

```
Unable to resolve "./NavigationContainer" from "node_modules/@react-navigation/core/src/index.tsx"
```

And this is a screenshot of the Samsung Galaxy S9 device:

![image](https://user-images.githubusercontent.com/1866564/73907719-fabcc600-48d9-11ea-8072-b0028e0f94a6.png)

Looking at `node_modules/@react-navigation/core/src/index.tsx`, this is the content and I do not see `NavigationContainer` exported:

```jsx
import * as CommonActions from './CommonActions';

export { CommonActions };

export { default as BaseRouter } from './BaseRouter';
export { default as BaseNavigationContainer } from './BaseNavigationContainer';
export { default as createNavigatorFactory } from './createNavigatorFactory';

export { default as NavigationContext } from './NavigationContext';
export { default as NavigationRouteContext } from './NavigationRouteContext';

export { default as useNavigationBuilder } from './useNavigationBuilder';
export { default as useNavigation } from './useNavigation';
export { default as useRoute } from './useRoute';
export { default as useFocusEffect } from './useFocusEffect';
export { default as useIsFocused } from './useIsFocused';
export { default as useNavigationState } from './useNavigationState';

export { default as getStateFromPath } from './getStateFromPath';
export { default as getPathFromState } from './getPathFromState';
export { default as getActionFromState } from './getActionFromState';

export * from './types';
```

Just to confirm the version used:

```
├─┬ @react-navigation/drawer@5.0.0
│ └─┬ @react-navigation/routers@5.0.0
│   └── @react-navigation/core@5.0.0  deduped
└─┬ @react-navigation/native@5.0.0
  └── @react-navigation/core@5.0.0 
```

Note that there are some other errors within my test since this upgrade:

```
    TypeError: Cannot read property 'split' of undefined

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:42:26)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:8:1)

```

**Comment by lucasluca** [comment]
Remove nodemodules and packagelock and then run the command -> react-native start --reset-cache

npm install

This worked for me.

**Comment by satya164** [comment]
> keep this open? user may post some solution. For example, Is there a way for me to play with v5 using jest mock?

If you have a different problem then open separate issue. Unable to resolve is different from what you're describing, and I cannot repro it.

**Comment by kopax** [comment]
Hello, the `jest-expo` fix has been released, however, I have a new error after upgrading my dependencies: 

```
    "@react-navigation/core": "^5.2.1",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
```

iOS and Android app gives the following error:


```
Unable to resolve module ./CommonActions from node_modules\@react-navigation\core\src\index.tsx:
```

Also, when using the `expo-dark-theme-switch`, it crash on Android, This doesn't happen with the alpha.


Running `expo start -c` didn't help. Any idea what's going on ? Thanks!
